=== thewizardplusplus/git-earliest-date/docs/schemas/repo_info_group.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/schemas/repo_info_group.schema.json",
  "title": "RepoInfoGroup",
  "type": "object",
  "required": [
    "repos",
    "is_empty",
    "author_earliest_repo",
    "committer_earliest_repo"
  ],
  "properties": {
    "repos": {
      "type": "array",
      "items": {
        "$ref": "repo_info.schema.json"
      }
    },
    "is_empty": {
      "type": "boolean"
    },
    "author_earliest_repo": {
      "oneOf": [{ "$ref": "repo_info.schema.json" }, { "type": "null" }]
    },
    "committer_earliest_repo": {
      "oneOf": [{ "$ref": "repo_info.schema.json" }, { "type": "null" }]
    }
  }
}

=== thewizardplusplus/git-earliest-date/docs/examples/repo_info_group.example.json
{
  "repos": [
    {
      "repo_dir": "/home/thewizardplusplus/projects/portfolio/go-exercises-frontend",
      "root_commits": [
        {
          "hash": "af693a2c15659e1a2a9e0e0fedc340b91ddf5576",
          "author": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "author_datetime": "2021-04-14T23:00:00.000000+03:00",
          "committer": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "committer_datetime": "2021-04-14T23:00:00.000000+03:00",
          "message": "Initialize the project using the Create React App tool\n"
        }
      ],
      "is_empty_repo": false,
      "author_earliest_root_commit": {
        "hash": "af693a2c15659e1a2a9e0e0fedc340b91ddf5576",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2021-04-14T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2021-04-14T23:00:00.000000+03:00",
        "message": "Initialize the project using the Create React App tool\n"
      },
      "committer_earliest_root_commit": {
        "hash": "af693a2c15659e1a2a9e0e0fedc340b91ddf5576",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2021-04-14T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2021-04-14T23:00:00.000000+03:00",
        "message": "Initialize the project using the Create React App tool\n"
      }
    },
    {
      "repo_dir": "/home/thewizardplusplus/projects/portfolio/go-hashmap",
      "root_commits": [
        {
          "hash": "1c58edfab26c8087db9610e5e3c77cfaeebd35b4",
          "author": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "author_datetime": "2019-04-30T00:56:14.000000+03:00",
          "committer": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "committer_datetime": "2019-04-30T02:08:45.000000+03:00",
          "message": "Add a base of the project\n"
        }
      ],
      "is_empty_repo": false,
      "author_earliest_root_commit": {
        "hash": "1c58edfab26c8087db9610e5e3c77cfaeebd35b4",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2019-04-30T00:56:14.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2019-04-30T02:08:45.000000+03:00",
        "message": "Add a base of the project\n"
      },
      "committer_earliest_root_commit": {
        "hash": "1c58edfab26c8087db9610e5e3c77cfaeebd35b4",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2019-04-30T00:56:14.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2019-04-30T02:08:45.000000+03:00",
        "message": "Add a base of the project\n"
      }
    },
    {
      "repo_dir": "/home/thewizardplusplus/projects/portfolio/go-atari-cli",
      "root_commits": [
        {
          "hash": "556257963e6c3ef8d747e117f1b51ec27dd33ec8",
          "author": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "author_datetime": "2020-04-29T23:00:00.000000+03:00",
          "committer": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "committer_datetime": "2020-04-29T23:00:00.000000+03:00",
          "message": ""
        }
      ],
      "is_empty_repo": false,
      "author_earliest_root_commit": {
        "hash": "556257963e6c3ef8d747e117f1b51ec27dd33ec8",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2020-04-29T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2020-04-29T23:00:00.000000+03:00",
        "message": ""
      },
      "committer_earliest_root_commit": {
        "hash": "556257963e6c3ef8d747e117f1b51ec27dd33ec8",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2020-04-29T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2020-04-29T23:00:00.000000+03:00",
        "message": ""
      }
    },
    {
      "repo_dir": "/home/thewizardplusplus/projects/portfolio/go-exercises-worker",
      "root_commits": [
        {
          "hash": "7296dbf4f9bd1befd84b6952d2a875c959c3a4f2",
          "author": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "author_datetime": "2021-03-26T23:00:00.000000+03:00",
          "committer": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "committer_datetime": "2021-03-26T23:00:00.000000+03:00",
          "message": "Add basics of the project\n"
        }
      ],
      "is_empty_repo": false,
      "author_earliest_root_commit": {
        "hash": "7296dbf4f9bd1befd84b6952d2a875c959c3a4f2",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2021-03-26T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2021-03-26T23:00:00.000000+03:00",
        "message": "Add basics of the project\n"
      },
      "committer_earliest_root_commit": {
        "hash": "7296dbf4f9bd1befd84b6952d2a875c959c3a4f2",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2021-03-26T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2021-03-26T23:00:00.000000+03:00",
        "message": "Add basics of the project\n"
      }
    },
    {
      "repo_dir": "/home/thewizardplusplus/projects/portfolio/go-cache",
      "root_commits": [
        {
          "hash": "645da77414f8eb7493d18eb906b8651d739a5c89",
          "author": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "author_datetime": "2019-07-02T23:00:00.000000+03:00",
          "committer": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "committer_datetime": "2019-07-02T23:00:00.000000+03:00",
          "message": "Add a base of the project\n"
        }
      ],
      "is_empty_repo": false,
      "author_earliest_root_commit": {
        "hash": "645da77414f8eb7493d18eb906b8651d739a5c89",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2019-07-02T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2019-07-02T23:00:00.000000+03:00",
        "message": "Add a base of the project\n"
      },
      "committer_earliest_root_commit": {
        "hash": "645da77414f8eb7493d18eb906b8651d739a5c89",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2019-07-02T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2019-07-02T23:00:00.000000+03:00",
        "message": "Add a base of the project\n"
      }
    },
    {
      "repo_dir": "/home/thewizardplusplus/projects/portfolio/go-exercises-backend",
      "root_commits": [
        {
          "hash": "af44933d833b4a11ce4e675145bd9405d760e86f",
          "author": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "author_datetime": "2021-03-22T23:00:00.000000+03:00",
          "committer": {
            "name": "thewizardplusplus",
            "email": "thewizardplusplus@yandex.ru"
          },
          "committer_datetime": "2021-03-22T23:00:00.000000+03:00",
          "message": "Add basics of the project\n"
        }
      ],
      "is_empty_repo": false,
      "author_earliest_root_commit": {
        "hash": "af44933d833b4a11ce4e675145bd9405d760e86f",
        "author": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "author_datetime": "2021-03-22T23:00:00.000000+03:00",
        "committer": {
          "name": "thewizardplusplus",
          "email": "thewizardplusplus@yandex.ru"
        },
        "committer_datetime": "2021-03-22T23:00:00.000000+03:00",
        "message": "Add basics of the project\n"
      },
      "committer_earliest_root_commit": {
        "hash": "af44933d833b4a11ce4e675145bd9405d760e86f",
